wandb_version: 1

algo:
  desc: null
  value: SAC
total_timesteps:
  desc: null
  value: 1000000
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 256
train_freq:
  desc: null
  value: 1
gradient_steps:
  desc: null
  value: 1
ent_coef:
  desc: null
  value: auto
env_config:
  desc: null
  value:
    url: http://127.0.0.1:5000
    actions:
    - ahu_oveFanSup_u
    - oveValCoi_u
    - oveValRad_u
    observations:
      time:
      - 0
      - 31536000
      reaTZon_y:
      - 200.0
      - 400.0
      reaCO2Zon_y:
      - 200.0
      - 2000.0
      weaSta_reaWeaTDryBul_y:
      - 250.0
      - 350.0
      PriceElectricPowerHighlyDynamic:
      - -0.4
      - 0.4
      LowerSetp[1]:
      - 280.0
      - 310.0
      UpperSetp[1]:
      - 280.0
      - 310.0
      UpperCO2[1]:
      - 0
      - 10000
    predictive_period: 18000
    scenario:
      electricity_price: highly_dynamic
    random_start_time: true
    max_episode_length: 259200
    step_period: 3600
    excluding_periods:
    - - 14947200
      - 22982400
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724077006
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 14
      - 16
      - 22
      - 23
      - 34
      - 37
      4: 3.10.11
      5: 0.17.7
      8:
      - 1
      - 5
      13: linux-x86_64
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 100000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1724077010743559739
tensorboard_log:
  desc: null
  value: results/SAC_AD1/Model1
_last_obs:
  desc: null
  value: "[[2.3653370e+06 2.9314999e+02 4.1867508e+02 2.7435043e+02 5.7330001e-02\n\
    \  5.5659998e-02 5.0930001e-02 5.0020002e-02 4.9589999e-02 4.9980000e-02\n  2.8814999e+02\
    \ 2.8814999e+02 2.8814999e+02 2.8814999e+02 2.8814999e+02\n  2.8814999e+02 3.0314999e+02\
    \ 3.0314999e+02 3.0314999e+02 3.0314999e+02\n  3.0314999e+02 3.0314999e+02 8.0000000e+02\
    \ 8.0000000e+02 8.0000000e+02\n  8.0000000e+02 8.0000000e+02 8.0000000e+02]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'True'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x744d48ce2770>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: "Box([  0.  200.  200.  250.   -0.4  -0.4  -0.4  -0.4  -0.4  -0.4 280.  280.\n\
    \ 280.  280.  280.  280.  280.  280.  280.  280.  280.  280.    0.    0.\n   0.\
    \    0.    0.    0. ], [3.1536e+07 4.0000e+02 2.0000e+03 3.5000e+02 4.0000e-01\
    \ 4.0000e-01\n 4.0000e-01 4.0000e-01 4.0000e-01 4.0000e-01 3.1000e+02 3.1000e+02\n\
    \ 3.1000e+02 3.1000e+02 3.1000e+02 3.1000e+02 3.1000e+02 3.1000e+02\n 3.1000e+02\
    \ 3.1000e+02 3.1000e+02 3.1000e+02 1.0000e+04 1.0000e+04\n 1.0000e+04 1.0000e+04\
    \ 1.0000e+04 1.0000e+04], (28,), float32)"
action_space:
  desc: null
  value: Box(0.0, 1.0, (3,), float32)
n_envs:
  desc: null
  value: 1
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.005
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x744d48ce2800>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -3.0
log_ent_coef:
  desc: null
  value: tensor([0.], requires_grad=True)
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x744d48ccb130>
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=28, out_features=256, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n\
    \    )\n    (mu): Linear(in_features=256, out_features=3, bias=True)\n    (log_std):\
    \ Linear(in_features=256, out_features=3, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=28,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256,\
    \ out_features=3, bias=True)\n  (log_std): Linear(in_features=256, out_features=3,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=31,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x744d4b64e7a0>
