wandb_version: 1

algo:
  desc: null
  value: SAC
total_timesteps:
  desc: null
  value: 1000000
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 256
train_freq:
  desc: null
  value: 1
gradient_steps:
  desc: null
  value: 1
ent_coef:
  desc: null
  value: auto
env_config:
  desc: null
  value:
    url: http://127.0.0.1:5000
    actions:
    - ahu_oveFanSup_u
    - oveValCoi_u
    - oveValRad_u
    observations:
      time:
      - 0
      - 31536000
      reaTZon_y:
      - 200.0
      - 400.0
      reaCO2Zon_y:
      - 200.0
      - 2000.0
      weaSta_reaWeaTDryBul_y:
      - 250.0
      - 350.0
      PriceElectricPowerHighlyDynamic:
      - -0.4
      - 0.4
      LowerSetp[1]:
      - 280.0
      - 310.0
      UpperSetp[1]:
      - 280.0
      - 310.0
      UpperCO2[1]:
      - 0
      - 10000
    predictive_period: 18000
    scenario:
      electricity_price: highly_dynamic
    random_start_time: true
    max_episode_length: 259200
    step_period: 3600
    excluding_periods:
    - - 14947200
      - 22982400
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724076943
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 16
      - 22
      - 23
      - 34
      - 37
      4: 3.10.11
      5: 0.17.7
      8:
      - 1
      - 5
      13: linux-x86_64
